<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyCollectionLib\MyCollectionLib.csproj" />
    <ProjectReference Include="..\MyNewCollection\MyNewCollectionLib.csproj" />
    <ProjectReference Include="..\Organization\OrganizationLib.csproj" />
  </ItemGroup>

</Project>
